## 1. Array Operations

### 1.1. Arithmetic Operations

In [2]:
! pip install numpy as np

ERROR: Could not find a version that satisfies the requirement as (from versions: none)
ERROR: No matching distribution found for as


In [1]:
import numpy as np 

# 1D Arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Addition
print(arr1 + arr2)

# Subtraction
print(arr1 - arr2)

# Multiplication
print(arr1 * arr2)

# Division
print(arr1 / arr2)


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [12]:
import numpy as np
arr = np.empty((2, 3))
print(arr)  
# random garbage values (jo memory me padhe hain)

arr = np.array([1, 2, 3], dtype=np.int32)
print(arr.itemsize)  # 4 bytes


arr11 = np.random.randn(2, 2)
print(arr11)


[[3.5e-323 4.0e-323 4.4e-323]
 [4.9e-323 5.4e-323 5.9e-323]]
4
[[-1.33112218  1.24873219]
 [ 0.42324857  0.04083181]]


In [2]:
# 2D Array
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

result_add = arr1 + arr2
print("Addition:\n", result_add)

result_subtract = arr1 - arr2
print("\nSubtraction:\n", result_subtract)

result_multiply = arr1 * arr2
print("\nMultiplication:\n", result_multiply)

result_divide = arr1 / arr2
print("\nDivision:\n", result_divide)

Addition:
 [[ 6  8]
 [10 12]]

Subtraction:
 [[-4 -4]
 [-4 -4]]

Multiplication:
 [[ 5 12]
 [21 32]]

Division:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


### 1.2. Scalar Operations

In [3]:
# 1D Array
arr = np.array([1, 2, 3])

# Scalar addition
print(arr + 10)

# Scalar multiplication
print(arr * 2)


[11 12 13]
[2 4 6]


In [4]:
# 2D Array
arr = np.array([[1, 2], [3, 4]])

result_add = arr + 10
print("Addition with scalar 10:\n", result_add)

result_subtract = arr - 5
print("\nSubtraction with scalar 5:\n", result_subtract)

result_multiply = arr * 2
print("\nMultiplication with scalar 2:\n", result_multiply)

result_divide = arr / 2
print("\nDivision by scalar 2:\n", result_divide)

result_power = arr ** 3
print("\nPower of 3:\n", result_power)


Addition with scalar 10:
 [[11 12]
 [13 14]]

Subtraction with scalar 5:
 [[-4 -3]
 [-2 -1]]

Multiplication with scalar 2:
 [[2 4]
 [6 8]]

Division by scalar 2:
 [[0.5 1. ]
 [1.5 2. ]]

Power of 3:
 [[ 1  8]
 [27 64]]


### 1.3. Element-wise Functions

In [5]:
# 1D Array
arr = np.array([1, 2, 3])

# Square root
print(np.sqrt(arr))

# Exponential
print(np.exp(arr))

# Logarithm
print(np.log(arr))


[1.         1.41421356 1.73205081]
[ 2.71828183  7.3890561  20.08553692]
[0.         0.69314718 1.09861229]


In [6]:
# 2D Array
arr_2d = np.array([[1, 2], [3, 4]])

print("Square root:\n", np.sqrt(arr_2d))

print("\nExponential:\n", np.exp(arr_2d))

print("\nLogarithm:\n", np.log(arr_2d))


Square root:
 [[1.         1.41421356]
 [1.73205081 2.        ]]

Exponential:
 [[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]

Logarithm:
 [[0.         0.69314718]
 [1.09861229 1.38629436]]


## 2. Array Manipulation

### 2.1. Concatenation

In [7]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Concatenate 1D arrays
arr_concat = np.concatenate((arr1, arr2))
print(arr_concat)


[1 2 3 4 5 6]


In [8]:
# row-wise concatenation of 2D Arrays
arr1_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr2_2d = np.array([[7, 8, 9], [10, 11, 12]])

row_concat = np.concatenate((arr1_2d, arr2_2d), axis=0)
print(row_concat)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [9]:
# column-wise concatenation of 2D Arrays
arr1_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr2_2d = np.array([[7, 8, 9], [10, 11, 12]])

col_concat = np.concatenate((arr1_2d, arr2_2d), axis=1)
print(col_concat)


[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


### 2.2. Stacking

In [3]:

import numpy as np

arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

# Vertical stack
arr_vstack = np.vstack((arr1, arr2))
print(arr_vstack)

# Horizontal stack
arr_hstack = np.hstack((arr1, arr2))
print(arr_hstack)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [11]:
arr1_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr2_2d = np.array([[7, 8, 9], [10, 11, 12]])

# Vertical stack
vstack_2d = np.vstack((arr1_2d, arr2_2d))
print("Vertical Stack of 2D arrays:\n", vstack_2d)

# Horizontal stack
hstack_2d = np.hstack((arr1_2d, arr2_2d))
print("\nHorizontal Stack of 2D arrays:\n", hstack_2d)


Vertical Stack of 2D arrays:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Horizontal Stack of 2D arrays:
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


### 2.3. Splitting

In [7]:
arr = np.array([1, 2, 3, 4, 5, 6])

# Splitting into 3 sub-arrays
arr_split = np.split(arr, 2)
print(arr_split)




[array([1, 2, 3]), array([4, 5, 6])]


In [13]:
# splitting along rows
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

split_rows = np.split(arr_2d, 3, axis=0)
print(split_rows)


[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [14]:
# splitting along columns
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

split_cols = np.split(arr_2d, 3, axis=1)
print(split_cols)


[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


### 3. Linear Algebra

### 3.1. Dot Product

In [15]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

dot_product = np.dot(arr1, arr2)
print(dot_product)


32


In [16]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# dot product of 2D arrays is matrix multiplication
dot_product = np.dot(A, B)
print(dot_product)

[[19 22]
 [43 50]]


In [17]:
at_product = A @ B
print(at_product)


[[19 22]
 [43 50]]


### 3.2. Matrix Multiplication

In [18]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

matrix_product = np.matmul(matrix1, matrix2)
print(matrix_product)


[[19 22]
 [43 50]]


## 4. Broadcasting
Broadcasting allows NumPy to perform operations on arrays of different shapes

### 4.1. Broadcasting with Scalars

In [19]:
import numpy as np

arr = np.array([1, 2, 3])
result = arr + 5 
print("1D: ", result)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
result = arr_2d * 10
print("2D: \n", result)

1D:  [6 7 8]
2D: 
 [[10 20 30]
 [40 50 60]]


### 4.2. Broadcasting with Arrays

In [9]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([[1], [2], [3]])
p=np.shape(arr1)
print(p)
q=np.shape(arr2)
print(q)

result = arr1 + arr2
print(result)

(3,)
(3, 1)
[[2 3 4]
 [3 4 5]
 [4 5 6]]


## 5. Conditional/selection np.where function

In [1]:
import numpy as np

a = np.array([1,2,3,10,5,6])
x = np.where(a>2)
x

(array([2, 3, 4, 5], dtype=int64),)

In [2]:
a = np.array([3, -1, 2, -5])
np.where(a >= 0, 1, 0)  

array([1, 0, 1, 0])

In [3]:
a = np.array([3, -1, 2, -5])
np.where(a >= 0, a, 0)  

array([3, 0, 2, 0])

In [4]:
x = np.array([10, 20, 30, 40])
y = np.array([1,  2,  3,  4])
cond = np.array([True, False, True, False])
np.where(cond, x, y) 

array([10,  2, 30,  4])

In [8]:
import numpy as np
h=1.5
v=20
g=9.8

angles_Deg=np.array([0,15,30,45,60,75,90])
radians=np.radians(angles_Deg)

new_Range=(v*np.cos(radians)/g)*(v*np.sin(radians)+np.sqrt((v*np.sin(radians))**2+2*g*h))
new_height=h+(((v*np.sin(radians))**2)/(2*g))
#height
maxi=np.max(new_height)
#range
max_m=np.max(new_Range)
# for index angles
H=angles_Deg[np.argmax(new_height)]
R=angles_Deg[np.argmax(new_Range)]
print("Maximum Height: {:.2f} m at angle {}°".format(maxi, H))
print("Maximum Range: {:.2f} m at angle {}°".format(max_m, R))

Maximum Height: 21.91 m at angle 90°
Maximum Range: 42.26 m at angle 45°
